### ISSUE TITLE
Incorrect Date Key

### ISSUE THREAD

**Issue by qpowell** [Brideau/pokelyzer#11]
So far, I've only collected data on the night of 7/27 and during the day on 7/28. I've noticed a couple entries in my dataset that have a date key of 20160718. Any idea what could be causing this?

I wasn't sure if this was something from the restore or not. I know this project is getting a ton of attention right now so I understand if you're busy. No rush on a response, was just curious.

Thanks :)

**Comment by Brideau** [comment]
What's happening is that we're receiving data from some Pokemon that have a "Time Until Hidden" that's a huge negative number for some reason. When you add that time to the current date and time, it goes way back in the past and that's the timestamp you see.

The quick solution, since there isn't that many of these (at least in my set - is there in yours?), is to just filter out any rows of data that have a negative value for Time Until Hidden. This is the only clean solution I can think of since if you try to use a timestamp of when the record was stored in the database, you have to assume that the data is arriving in some sensible order and timeliness, which I don't think it is.

**Comment by qpowell** [comment]
Makes sense, I filtered it out according to the tutorial but I didn't realize those were related :) I'm still trying to make sense of what all the fields are. Which attribute corresponds to the time the pokemon showed up on the map? I'm trying to work on converting this to localtime in Tableau :)

Thanks again for the quick response.

**Comment by Brideau** [comment]
I'm just going to leave this thread open since a lot of people have the same question and it's easier to find this way :)

When a Pokemon appears is a mystery. We only receive data if somebody spots them in the wild. ("If a Pokemon appears in the wild, and no one's around to catch it, does it produce an event"?) Because of that the best we can do is record the time we received the event and the time it will disappear since we are given that information.

Because of this, all of the time fields in the time dimension are tied to the disappearance time. It's not perfect, but it works.

If you come up with a solution for the timezone issue in Tableau, please add it to the Wiki! I have a ticket open for a proper solution (https://github.com/Brideau/pokelyzer/issues/12) but it would be great to have a stopgap for now.

**Comment by qpowell** [comment]
@Brideau I've tried a few things, but my lack of Tableau knowledge is making it difficult. I saw that you could access things like Quarter, Minute, Hour, Second, etc. of Hidden Time UTC, but I can't figure out how to leverage this data in a calculated field, or using the date format option when creating a Parameter for the field.

**Comment by Brideau** [comment]
Yeah I really need to do a tutorial on this. They key is to not bother using the Hidden Time UTC field, and instead use the dimensions in the `time_dimension` table, as they are both connected to the same data. 

Basically what the time dimension table does is let you "group by" each of the things in it. For example, you can group all the data by 30 min intervals using a 12-hour clock through the day by using the `label_30min_12' dimension.

**Comment by qpowell** [comment]
Aah, that makes way more sense than what I was trying to do. Even though there's still a timezone issue, all I have to do is think about the UTC time for the local time I'm looking for, and filter on that.  I'll probably just stick with that for now.

I did try some hacky stuff with creating a calculated field, and it kind of gave me what I wanted (a time 5 minutes before the hidden time, with my timezone offset subtracted from the hour):

`STR(SUM(DATEPART('hour', [Hidden Time Utc])-5)) + ":" + STR(SUM(DATEPART('minute', [Hidden Time Utc]) - 5))`

It 'worked', but that's so ugly to look at :) and also isn't very flexible. Looking forward to when someone smarter than me figures out a way to implement it, haha. Thanks for the help

**Comment by Brideau** [comment]
@qpowell I added a new patch that records the UTC timestamp at the time of insertion, so if you'd like to doing a time analysis based on that, that's a possibility as well. See the readme here: https://github.com/Brideau/pokelyzer

**Comment by Brideau** [comment]
@qpowell I know everything is down at the moment, but maybe this is a good time to do some database maintenance :) I've added support for local timezones in the newest patch here: https://github.com/Brideau/pokelyzer/wiki/Patches

**Comment by Brideau** [comment]
I'm going to close this for now, but feel free to open another ticket if there's any issues with my implementation of time zones.
