### ISSUE TITLE
Error fetching client from pool

### ISSUE THREAD

**Issue by madcapheathen** [Brideau/pokelyzer#29]
Hello, I'm cartoonishly inept at anything database-related, so I haven't been able to figure out where my problem is. I'm getting the following error after running Pokelyzer:

`{"name":"MainApp","hostname":"DESKTOP-NT6HCKO","pid":1092,"level":50,"msg":"Idle client error read ECONNRESET Error: read ECONNRESET\n    at exports._errnoException (util.js:873:11)\n    at TCP.onread (net.js:557:26)","time":"2016-07-31T23:22:04.260Z","v":0}
{"name":"MainApp","hostname":"DESKTOP-NT6HCKO","pid":1092,"level":50,"msg":"Error fetching client from pool { [error: password authentication failed for user \"pokemon_go_role\"]\n  name: 'error',\n  length: 104,\n  severity: 'FATAL',\n  code: '28P01',\n  detail: undefined,\n  hint: undefined,\n  position: undefined,\n  internalPosition: undefined,\n  internalQuery: undefined,\n  where: undefined,\n  schema: undefined,\n  table: undefined,\n  column: undefined,\n  dataType: undefined,\n  constraint: undefined,\n  file: 'auth.c',\n  line: '285',\n  routine: 'auth_failed' }","time":"2016-07-31T23:22:10.878Z","v":0}`

It looked to me like there was just a typo in my password, but I tried with and without quotes and double checked the spelling and the same error popped up every time. I did run the latest patch, but dropping the 'name' column from spotted_pokemon failed because the column didn't exist in the first place. Could that be the issue? A version mismatch between pokemon_go_db_backup and the instructions? I did also try deleting the database and starting with a fresh restore - same problem.

**Comment by Brideau** [comment]
Have you removed the quotes from the username as well?

**Comment by ghost** [comment]
Hello @Brideau 
I have a similar problem on Windows, I'll put it here since the issues/27 was closed.
I followed the installation instructions step by step and got to the last point, where after starting both the map and database scripts, a following error occurs:
http://i.imgur.com/VXyAeq8.png

The map script works fine - http://i.imgur.com/nfd2arg.png
I can see the map at: http://localhost:5000/

I'm using the latest build and pokemon_go_db_backup.tar file. All the mentioned above patches seems to be applied:
http://i.imgur.com/j5MQagx.png
http://i.imgur.com/dr23nrX.png

The error msg seems to be suggesting that I used the wrong password but I checked and even changed it several times - it is the same password as the one I've set here:
http://i.imgur.com/5054dKr.png

Please tell me what am I doing incorrectly.

Best Regards

---

Edit:
Using "set DB_USER=postgres" instead of "set DB_USER=pokemon_go_role" worked and now the database is being updated.

**Comment by Brideau** [comment]
Hey all, I'm just running through the Windows install now myself, as I didn't have access to a Windows machine before now. It sounds like the guide is pretty buggy given all the updates that have happened. I'll clean it up and get back to you ASAP.

**Comment by Brideau** [comment]
@madcapheathen @mateszbukaty My sincere apologies. After going through those docs, I'm surprised anybody managed to get it running. I've gone through everything step-by-step and found some major gaps.

Both of your errors were caused by a missing instruction step which specified how to set a password for the `pokemon_go_role` role. While you can get it to work with the `postgres` user, I would advise against it because that's generally bad security practice (even if this isn't high-stakes stuff). Have a look at the updated instructions and hopefully that will resolve these errors for both of you.

Apologies again - I should have verified the instructions personally before putting them up in the wiki.

**Comment by madcapheathen** [comment]
Just got home and read through all this, and yeah, wow, I feel a little stupid. I knew I was giving it the password for `postgres` but it didn't occur to me that other roles wouldn't share the same password. Everything works now, though - thanks so much for the prompt response and all your hard work!

**Comment by ghost** [comment]
Works like a charm now. Thanks for all the help!

**One final question:** does it matter that when I was restoring the database from pookemon_go_db_backup.tar file I've chosen Rolename: pokemon_go_role (like here: http://i.imgur.com/7JuQDgk.png) instead of leaving it blank? I did it when I was trying to figure out and fix the aforementioned password errors and then I couldn't change it back since I would have to delete both the current database and login role (and would lose all the data that I gathered over the night). I think it just added a lot of additional dependents. It currently looks like that: http://i.imgur.com/tein9BB.png. Probably it doesn't really matter but I'd rather be safe than sorry.

Cheers!

**Comment by Brideau** [comment]
@madcapheathen No problem!

@mateszbukaty In this instance it doesn't make a difference because the restore commands set the ownership of each table to pokemon_go_role, but in general it would be good practice just to be safe since that'll be the main user you're using with this particular database.
