### ISSUE TITLE
Exception: ReferenceError: Promise is not defined

### ISSUE THREAD

**Issue by maxwell-gregory** [Brideau/pokelyzer#45]
Looks like I am hitting an exception that is traces back to index.js

```
pi@raspberrypi:~/rep/pokelyzer $ DB_NAME='pokemon_go' DB_USER='pokemon_go_role' DB_PASS='********' DB_PORT=5432 WS_PORT=9876 ERA=2  node app.js | bunyan -l info

/home/pi/rep/pokelyzer/node_modules/pg/node_modules/pg-pool/index.js:11
  this.Promise = this.options.Promise || Promise
                                         ^
ReferenceError: Promise is not defined
    at module.exports (/home/pi/rep/pokelyzer/node_modules/pg/node_modules/pg-pool/index.js:11:42)
    at new BoundPool (/home/pi/rep/pokelyzer/node_modules/pg/lib/pool-factory.js:12:10)
    at Object.<anonymous> (/home/pi/rep/pokelyzer/app.js:19:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

**Comment by maxwell-gregory** [comment]
@Brideau Removing the specified `|| Promise` seems to fix the issue. Is this a bug?

**Comment by Brideau** [comment]
I can't even begin to explain what happened there. That's an error tossed up by the node postgres package...your guess is as good as mine for this one, since I don't see anything in your command that would have caused it.

**Comment by maxwell-gregory** [comment]
I am assuming I probably don't need that or statement? Was that a fallback?
Also a little off topic, can the DB variables be in a file? 
`DB_NAME='pokemon_go' DB_USER='pokemon_go_role' DB_PASS='********' DB_PORT=5432 WS_PORT=9876 ERA=2`

**Comment by Brideau** [comment]
I honestly have no clue since it's not code I wrote, just code from a package I used, and I can't produce the bug myself. What version of node are you running? Promises are a relatively recent invention.

You could put them in a file, I just don't like to leave files with passwords kicking around. With all the bugs it has kicked up though, I'm considering it.

**Comment by maxwell-gregory** [comment]
Just having trouble with `nohup` since the vars are declared before node, so i was gonna stash the DB vars in a file. Ill see what i can fudge with the "promise" bug, thanks

**Comment by vitaly-t** [comment]
This happens when running under Node.js prior to 0.12.x where type `Promise` wasn't supported.

It is due to poor promise support within `node-postgres`. I think there was a fix for this in the latest version, but I'm not sure.

If you want a better promise support for PostgreSQL, see [pg-promise](https://github.com/vitaly-t/pg-promise) :wink:
