### ISSUE TITLE
Rarity on tutorial does not match with latest db dump

### ISSUE THREAD

**Issue by viperfx** [Brideau/pokelyzer#61]
I made a fresh restore from your tar file today to start using the rarity column. However, I only see Common, Uncommon and Very Common. 

Unlike the screenshot shown in the tutorial here:

http://www.whackdata.com/2016/08/02/find-pokemon-by-rarity-pokelyzer/

**Comment by Brideau** [comment]
Did you do that before or after this commit today? https://github.com/Brideau/pokelyzer/commit/bb0a129988f462ae100426017cb318e3def3d169

**Comment by viperfx** [comment]
After. I downloaded the tar this morning on commit b179392

**Comment by Brideau** [comment]
Ohhhh, wait a second. It's because you're doing a left-join. Left joins take all of the records from the left table (that is, each row of spotted_pokemon), and only those rows from the right table (pokemon_info) that match to one in the left. In this instance, you simply didn't detect any Pokemon that weren't either Common, Uncommon or Very Common.

**Comment by Brideau** [comment]
@viperfx It ok for me to close this now?

**Comment by viperfx** [comment]
Yep, that makes sense to me. Thanks.
